image: gradle:alpine

stages:
  - Trigger Build
  - SCA/SAST
  - Result Report
  - Deploy
  - DAST/IAST
  - Aggregate Vulnerability Data
  - Remediation

Build-Application:
  stage: Trigger Build
  script: gradle --build-cache assemble

SCA:
  stage: SCA/SAST
  script:
    - echo "Software Composition Analysis (SCA)"


SAST:
  stage: SCA/SAST 
  script:
    - echo "Static Application Security Testing (SAST)"

Report:
  stage: Result Report 
  script:
    - echo "Ci/CD result report"


faild buid:      # This job runs in the deploy stage.
  stage: Deploy  # It only runs when *both* jobs in the test stage complete successfully.
#   rules:
#     - if: $test == "faild"
#       when: manual
  script:
    - echo "Severe Issuses Found"

Alert:      # This job runs in the deploy stage.
  stage: Deploy  # It only runs when *both* jobs in the test stage complete successfully.
#   rules:
#     - if: $test == "faild"
#       when: manual
  script:
    - echo "Issue found"

Deploy to Nonprod:
#   environment: non-prod
  stage: Deploy  # It only runs when *both* jobs in the test stage complete successfully.
#   rules:
#     - if: $test == "faild"
#       when: manual
  script:
    - echo "No Issue Found"

Deploy to Nonprod (Issue found):
#   environment: non-prod
  stage: Deploy  # It only runs when *both* jobs in the test stage complete successfully.
#   rules:
#     - if: $test == "faild"
#       when: manual
  script:
    - echo "Issue Found but not severe"

DAST/IAST:
#   environment: non-prod
  stage: DAST/IAST  # It only runs when *both* jobs in the test stage complete successfully.
#   rules:
#     - if: $test == "faild"
#       when: manual
  script:
    - echo "CI/CD server initiates DAST/IAST"

Result from DAST/IAST:
#   environment: non-prod
  stage: DAST/IAST  # It only runs when *both* jobs in the test stage complete successfully.
#   rules:
#     - if: $test == "faild"
#       when: manual
  script:
    - echo "Process results in CI/CD Server"
