image: vubuivn/java-gradle-maven:1.0.0

stages:
  - Trigger Build
  - SCA/SAST
  - Result Report
  - Deploy
  - DAST/IAST
  - Aggregate Vulnerability Data
  - Remediation
  - Release

Check version:
  stage: Trigger Build
  script: java --version && gradle --version

# Build-Application:
#   stage: Trigger Build
#   script: gradle --build-cache assemble

Package Docker Image:
  stage: Trigger Build
  script: 
    - echo "docker syntax for docker build image"

SCA:
  stage: SCA/SAST
  script:
    - echo "Software Composition Analysis (SCA)"

SAST:
  stage: SCA/SAST 
  script:
    - echo "Static Application Security Testing (SAST)"

Report:
  stage: Result Report 
  script:
    - echo "Report result is $build_result"

faild buid:
  stage: Deploy
  rules:
    - if: $build_result == "faild"
  script:
    - echo "Severe Issuses Found"

Alert:
  stage: Deploy
  rules:
    - if: $build_result == "atler"
  script:
    - echo "Issue found but not severe, start to push package"

Prepare ECR key and Nexus Key:
  stage: Deploy
  rules:
    - if: $build_result == "success" || $build_result == "atler"
  script:
    - echo "Prepare ECR key and Nexus Key"

Push Package to Artifactory:
  stage: Deploy
  rules:
    - if: $build_result == "success" || $build_result == "atler"
  script:
    - echo "docker login from ECR - and n"
    - echo "push image to ECR & push binary to Nixus"
    - echo "docker login --username --password"
    - SET "NEXUS_USERNAME=joebob" && SET "NEXUS_PASSWORD=password" && curl -v -u %NEXUS_USERNAME%:%NEXUS_PASSWORD% --upload-file %UPLOAD_FILE% http://%NEXUS_SERVER%/repository/%NEXUS_REPOSITORY%/%UPLOAD_FILE%

Deploy to Nonprod:
  stage: Deploy
  rules:
    - if: $build_result == "success" || $build_result == "atler"
      when: never
  script:
    - echo "helm upgrade --install"

DAST/IAST:
  stage: DAST/IAST
  rules:
    - if: $build_result == "faild"
      when: never
  script:
    - echo "CI/CD server initiates DAST/IAST"

Result from DAST/IAST:
  stage: DAST/IAST
  script:
    - echo "Process results in CI/CD Server"

Collect data from "build report":
  stage: Aggregate Vulnerability Data
  rules:
    - if: $build_result == "faild"
  script:
    - echo "start to Aggregate data from Build Report"

Collect data from "deploy report":
  stage: Aggregate Vulnerability Data
  rules:
    - if: $deploy_result == "faild"
  script:
    - echo "start to Aggregate data from deploy Report"

Log Ticket:
  stage: Remediation
  # rules:
  #   - if: $deploy_result == "faild"
  script:
    - echo "Start to log ticket"

Close Ticket:
  stage: Release
  # rules:
  #   - if: $deploy_result == "faild"
  script:
    - echo "Close Ticket"