image: gradle:alpine

stages:
  - Trigger Build
  - SCA/SAST
  - Result Report
  - Deploy
  - DAST/IAST
  - Aggregate Vulnerability Data
  - Remediation

Build-Application:
  stage: Trigger Build
  script: gradle --build-cache assemble

SCA:
  stage: SCA/SAST
  script:
    - echo "Software Composition Analysis (SCA)"


SAST:
  stage: SCA/SAST 
  script:
    - echo "Static Application Security Testing (SAST)"

Report:
  stage: Result Report 
  script:
    - echo "Ci/CD result report"


faild buid:
  stage: Deploy
  rules:
    - if: $Build_Result == "faild"
  script:
    - echo "Severe Issuses Found"

Alert:
  stage: Deploy  
  rules:
    - if: $Build_Result == "faild"
  script:
    - echo "Issue found"

Deploy to Nonprod:
#   environment: non-prod
  stage: Deploy  
  rules:
    - if: $Build_Result != "faild"
  script:
    - echo "No Issue Found"

Deploy to Nonprod (Issue found):
#   environment: non-prod
  stage: Deploy  
  rules:
    - if: $Build_Result != "faild"
  script:
    - echo "Issue Found but not severe"

DAST/IAST:
#   environment: non-prod
  stage: DAST/IAST  
  rules:
    - if: $test != "faild"
  script:
    - echo "CI/CD server initiates DAST/IAST"

Result from DAST/IAST:
#   environment: non-prod
  stage: DAST/IAST 
  rules:
    - if: $test == "faild"
  script:
    - echo "Process results in CI/CD Server"
