image: gradle:alpine

stages:
  - Trigger Build
  - SCA/SAST
  - Result Report
  - Deploy
  - DAST/IAST
  - Aggregate Vulnerability Data
  - Remediation
  - Release

Build-Application:
  stage: Trigger Build
  script: gradle --build-cache assemble


Package Docker Image:
  stage: Trigger Build
  script: echo "DOCKER_BUILDKIT=1 docker build ....""

SCA:
  stage: SCA/SAST
  script:
    - echo "Software Composition Analysis (SCA)"

SAST:
  stage: SCA/SAST 
  script:
    - echo "Static Application Security Testing (SAST)"

Report:
  stage: Result Report 
  script:
    - echo "Report result is $build_result"

faild buid:
  stage: Deploy
  rules:
    - if: $build_result == "faild"
  script:
    - echo "Severe Issuses Found"

Alert:
  stage: Deploy
  rules:
    - if: $build_result == "faild"
      when: never
  script:
    - echo "Issue found but not severe"

Push Package to Artifactory:
  stage: Deploy
  rules:
    - if: $build_result == "faild"
      when: never
  script:
    - echo "push package to artifactory && docker push"

Deploy to Nonprod:
  stage: Deploy
  rules:
    - if: $build_result == "faild"
      when: never
  script:
    - echo "helm upgrade --install"

Deploy to Nonprod (Issue found):
  stage: Deploy  
  rules:
    - if: $build_result == "faild"
      when: never
  script:
    - echo "Issue Found but not severe"
    - echo "helm upgrade --install"

DAST/IAST:
  stage: DAST/IAST
  rules:
    - if: $build_result == "faild"
      when: never
  script:
    - echo "CI/CD server initiates DAST/IAST"

Result from DAST/IAST:
  stage: DAST/IAST
  script:
    - echo "Process results in CI/CD Server"

Collect data from "build report":
  stage: Aggregate Vulnerability Data
  rules:
    - if: $build_result == "faild"
  script:
    - echo "start to Aggregate data from Build Report"

Collect data from "deploy report":
  stage: Aggregate Vulnerability Data
  rules:
    - if: $deploy_result == "faild"
  script:
    - echo "start to Aggregate data from deploy Report"

Log Ticket:
  stage: Remediation
  # rules:
  #   - if: $deploy_result == "faild"
  script:
    - echo "Start to log ticket"

Close Ticket:
  stage: Release
  # rules:
  #   - if: $deploy_result == "faild"
  script:
    - echo "Close Ticket"